### ISSUE TITLE
AwesomeWM widget not updating

### ISSUE THREAD

**Issue by ZedCee** [NuckChorris/assault#16]
The widget for AwesomeWM doesn't appear to be updating.  This is the second time I've used assault so it could be user error, but I don't recall having a refresh time to set to it.  
Presently the widget only updates on AwesomeWM reset _(`super + ctrl + r` is the default hot key)_.  
OS: Arch Linux
Awesome: v3.5.2-1846-gd3ccd04

**Comment by NuckChorris** [comment]
I don't use AwesomeWM any more (I've actually switched to OSX as my daily driver) but I'll get a VM running this weekend and see if I can reproduce :thumbsup:

**Comment by ZedCee** [comment]
Seems my :+1: didn't stick.
Thanks for looking into this.

**Comment by ZedCee** [comment]
Have you found the time to take a peek?

**Comment by traverseda** [comment]
Bump
